logging:
  level:
    org.ametiste: WARN

spring:
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    # url: jdbc:h2:file:./target/h2db/db/test-db;MODE=MySQL;DB_CLOSE_DELAY=-1

org:
  ametiste:
    routine:
      mod:
        backlog:
          enabled: true
          renewRate: 1115000