logging:
  level:
    org.ametiste: TRACE
    org.ametiste.metrics: ERROR
    # org.ametiste.routine.printer.backlog.PrintTaskPopulationStrategy: DEBUG
    org.ametiste.routine.mod.backlog.application.service.BacklogRenewService: DEBUG
    org.ametiste.routine.application.action.TaskTimeoutAction: DEBUG
    org.ametiste.routine.application.service.removing.DefaultTaskRemovingService: DEBUG

spring:
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate.hbm2ddl.import_files: update.sql
#      hibernate.hbm2ddl.auto: create-drop
  datasource:
     url: jdbc:h2:mem:ame_routine;MODE=MySQL;DB_CLOSE_DELAY=-1

org:
  ametiste:
    routine:
      core:
        initialExecutionConcurrency: 5
### Protocols Configuration

      protocol:
        http:
          enabled: true

### Mods Configuration

      mod:

        task-timeout:
          enabled: false

        startup:
          cleanup:
            enabled: false

        backlog:
          enabled: true
          renewRate: 5000

        shredder:
          enabled: true
          shreddingRate: 10000
          staleStates: DONE
          staleThreshold:
            value: 10
            unit: SECONDS

### App Configuration

      eg:
        printer:
          delayTime: 200000
          populationCount: 1

server:
  port: 8081
