logging:
  level:
    org.ametiste: DEBUG

spring:
  jpa:
    show-sql: false
  h2:
    console:
      enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ame_routine;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    # url: jdbc:h2:file:./target/h2db/db/test-db;MODE=MySQL;DB_CLOSE_DELAY=-1

org:
  ametiste:
    routine:
      mod:
        backlog:
          enabled: true
          renewRate: 5000