logging:
  level:
    org.ametiste: DEBUG

spring:
  jpa:
    show-sql: false
  datasource:
    url: jdbc:h2:mem:ame_routine;MODE=MySQL;DB_CLOSE_DELAY=-1

org:
  ametiste:
    routine:
      mod:
        backlog:
          enabled: true
          renewRate: 5000

server:
  port: 8081
