logging:
  level:
    org.ametiste: WARN
    org.ametiste.routine.printer.backlog.PrintTaskPopulationStrategy: DEBUG
    org.ametiste.routine.mod.backlog.application.service.BacklogRenewService: DEBUG

spring:
  jpa:
    show-sql: false
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:ame_routine;MODE=MySQL;DB_CLOSE_DELAY=-1

org:
  ametiste:
    routine:
      startup:
        cleanup:
          enabled: true
      eg:
        printer:
          delayTime: 2000
          populationCount: 10
      mod:
        backlog:
          enabled: true
          renewRate: 5000

server:
  port: 8081
