logging:
  level:
    org.ametiste: TRACE
    org.ametiste.metrics: ERROR
    # org.ametiste.routine.printer.backlog.PrintTaskPopulationStrategy: DEBUG
    org.ametiste.routine.mod.backlog.application.service.BacklogRenewService: DEBUG
    org.ametiste.routine.application.action.TaskTimeoutAction: DEBUG
    org.ametiste.routine.application.service.removing.DefaultTaskRemovingService: DEBUG
org:
  ametiste:
    routine:
### Mods Configuration
      mod:
        task-timeout:
          enabled: false
        startup:
          cleanup:
            enabled: false
        backlog:
          enabled: true
          renewRate: 5000
        shredder:
          enabled: true
          shreddingRate: 10000
          staleStates: DONE
          staleThreshold:
            value: 10
            unit: SECONDS
### App Configuration
      eg:
        printer:
          delayTime: 2000
          populationCount: 1
server:
  port: 8081
